- .gitignore
- build.sbt
- examples/src/main/scala/cats.scala
- examples/src/main/scala/example.scala
- tests/shared/src/main/scala/magnolia/cats.scala
- tests/shared/src/main/scala/magnolia/main.scala
Adds the implicits required to derive `cats.Show` type classes to the examples project and also adds a runnable test in the tests project.
> Add ContravariantDerivation for cats.Show to examples

- build.sbt
- core/src/main/scala/magnolia.scala
- examples/src/main/scala/show.scala
- tests/src/main/scala/tests.scala
The `Typeclass[T]` definition may now be included in a parent class/trait of the derivation object, which means that derivation objects may now be generic in other dimensions.
> Allow type constructor in supertrait

- core/shared/src/main/scala/globalutil.scala
- core/shared/src/main/scala/magnolia.scala
- tests/src/main/scala/tests.scala
That method is a workaround for a bug.
It doesn't belong in the core Magnolia macro. Also:
* Use `patchedCompanionRef` consistently
* Add a test for the workaround (method-local classes)
Follow up #39 it was merged before I could explain what I actually meant by local classes :smile:
> Move pathedCompanionRef to a GlobalUtil object

- core/shared/src/main/scala/magnolia.scala
- tests/src/main/scala/tests.scala
[This commit](https://github.com/propensive/magnolia/commit/c91b7cac849237062eea8a75134783e826dc21a0) introduced a regression that broke things like `Show.gen[List[Int]]`.
This patch selectively rolls back the changes from that commit, which green-lights the added test.
I have to say that I have absolutely no insight whatsoever into the intricacies of the name resolution here, so a proper review by @propensive and @joroKr21 is probably of the essence.
> Fix regression introduced by move to `patchedCompanionRef`

- build.sbt
for the Scala community build, for use with Scala nightly builds,
and so on
> handle more diverse Scala version numbers

- core/shared/src/main/scala/magnolia.scala
- tests/src/main/scala/tests.scala
It is required for the type checking of recursive typeclasses.
Including some test clarifications and minor improvements of the implementation
(look at individual commit messages).
fixes #87 
Unfortunately to verify this we would need to add a test that is not in the `magnolia` package.
Let me know if and how to do that if necessary.
> Make Deferred public (but compileTimeOnly)

- core/shared/src/main/scala/magnolia.scala
> Use encodedName to avoid invalid identifier names

- core/shared/src/main/scala/magnolia.scala
Method `checkMethod` is not using `termName` in the error message.
> checkMethod: termName is not used in the error message

- core/shared/src/main/scala/magnolia.scala
- examples/shared/src/main/scala/csv.scala
- tests/src/main/scala/tests.scala
when subtrees are Deferred or reference enclosing vals.
> Use strict vals by default and fall back to lazy vals

- core/shared/src/main/scala/interface.scala
- examples/shared/src/main/scala/default.scala
- examples/shared/src/main/scala/semiauto.scala
- project/build.properties
- tests/src/main/scala/tests.scala
> econstruct, like scalaz.MonadError.emap

- core/shared/src/main/scala/interface.scala
- core/shared/src/main/scala/magnolia.scala
- examples/shared/src/main/scala/semiauto.scala
- tests/src/main/scala/tests.scala
The motivation for this PR is that it allows one to derive an ADT but without it escaping into other people's types. Combined with the `@deriving` annotation it means we can write this
```scala
@deriving(Show, Equal, Arbitrary)
sealed abstract class JsValue
final case object JsNull                                    extends JsValue
final case class JsObject(fields: IList[(String, JsValue)]) extends JsValue
final case class JsArray(elements: IList[JsValue])          extends JsValue
final case class JsBoolean(value: Boolean)                  extends JsValue
final case class JsString(value: String)                    extends JsValue
final case class JsDouble(value: Double)                    extends JsValue
final case class JsInteger(value: Long)                     extends JsValue
``` …
> semiauto derivation if gen is not implicit

- core/shared/src/main/scala/interface.scala
- core/shared/src/main/scala/magnolia.scala
Maybe this should be 2 PR but given how simple it is maybe not.
- Make CallByNeed `Serializable` is pretty much self explanatory
- `Make TypeName.full a val` is for perf reason.  It gets expensive if called repeatedly.
> Make CallByNeed Serializable and Typename.full a val

- examples/shared/src/main/scala/default.scala
When we went over this example at Scale By the Bay, I was really confused about the different things with different purposes that were all named `default` and I thought it would be easier to read if they had slightly different names to convey their different uses. It does make it less concise but I think that is a tradeoff worth making -- feel free to let me know and reject this PR if you disagree. 
Note that due to https://github.com/propensive/magnolia/issues/144 I was unable to check that it still compiles. The changes are fairly minor so I'm not too concerned, but possibly someone else who can successfully run it should check before merge.
> Rename confusing default in example

- core/shared/src/main/scala/interface.scala
- core/shared/src/main/scala/magnolia.scala
- examples/shared/src/main/scala/show.scala
- examples/shared/src/main/scala/typename.scala
- tests/src/main/scala/tests.scala
This PR:
- adds type argument names to `TypeName`
- demonstrates use of type arguments with the Show type class example.
> Type arguments names (#148)

- core/shared/src/main/scala/magnolia.scala
Using `F[_]` causes a warning:
```
type parameter F defined in method constructMonadic shadows type F defined in class (...). You may want to rename your type parameter, or possibly remove it.
```
each time magnolia is invoked in a context which is parametrised using `F[_]` itself.
> Use a rarely used name for the monad type parameter in constructMonadic

- core/shared/src/main/scala/magnolia.scala
- tests/src/main/scala/JavaExampleAnnotation.java
- tests/src/main/scala/tests.scala
Java annotations are instantiated in a different way than Scala annotations (which are usually case classes, unlike Java annotations which are interfaces) - by overriding interface methods, instead of passing constructor parameters.
I tried doing that instead of passing the whole annotation call's tree, but apparently something in Scala makes it impossible to instantiate a Java annotation and actually grab an instance.
Should fix #103
> Support Java annotations by ignoring them!

- .travis.yml
- scripts/decrypt_files_if_not_pr.sh
Travis security policy is to not allow accessing secret variables during pull requests builds. Any attempt to do that will result in a failed build. So it is much better to just skip decrypting and let tests run.
> Fix travis pipeline for PRs 

- core/shared/src/main/scala/magnolia.scala
- tests/src/main/scala/tests.scala
When we fail to find a chained implicit in `typeclassTree`
we still want to pop the stack, otherwise the logic is broken.
On the other hand we want to keep the failed stack frames
in order to preserve the context for building a nice error message.
The problem is that `c.inferImplicitValue` is silent.
We solve the problem by keeping error frames in a separate stack.
When building the stack trace we put failed frames back on top.
Also factor out `magnolia:` prefix of error messages.
Fixes #154 (possibly others issues?)
Fixes #178 (second commit)
> Pop the stack on chained implicits and accumulate errors

- core/shared/src/main/scala/magnolia.scala
- examples/shared/src/main/scala/eq.scala
- tests/src/main/scala/tests.scala
Trees containing `Deferred` references might not be self contained
(this is the reason `Deferred` exists in the first place) and should
not be cached. We need to introduce a `shouldCache` parameter to
`recurse` because we have no access to the macro context in `Stack`.
* Introduce `shouldCache` predicate on trees to `recurse`
* Introduce `DeferredRef` tree constructor / extractor
* Don't cache trees that contain `Deferred` references
* Factor out `Stack.within` method to do `push` and `pop`
* Expand `recurse` body into pattern matches for clarity
Fixes #185 
P.s. I'm wondering if the cache pulls it's own weight after this.
> Don't cache trees containing Deferred references

- core/shared/src/main/scala/magnolia.scala
- examples/shared/src/main/scala/JavaAnnotatedCase.scala
- tests/src/main/scala/tests.scala
This fixes #187 
I know that this is rather a workaround than a proper fix, but I'm not expecting `isJavaAnnotation` to be fixed soon and this issue is quite annoying.
> Replace buggy typeSymbol.isJavaAnnotation with a custom solution

- core/shared/src/main/scala/interface.scala
- core/shared/src/main/scala/magnolia.scala
- examples/shared/src/main/scala/decodeSafe.scala
Closes #181.
This PR adds a `constructEither` method that allows users to construct case classes in a type safe manner given how to construct each field, where each field can fail with an error and where errors can be accumulated.
This is a special case of a more general `constructApplicative`, which I chose not to implement because we lack an `Applicative` type class and it's not easy to generate one like we do with `Monad` (see my comment in https://github.com/propensive/magnolia/issues/181#issuecomment-542895033). While less general, this method should still be useful for most purposes where people would use `Applicative`.
I tested this by running the following file in `examples/shared/src/main/scala`:
```scala
import scala.language.experimental.macros
import scala.language.higherKinds …
```
> Add `constructEither` to `CaseClass`

- core/shared/src/main/scala/magnolia.scala
- examples/shared/src/main/scala/typename.scala
- tests/src/main/scala/tests.scala
This PR closes #195.
NB I reused `TypeNameInfo` to test the order of sealed traits but happy to introduce a new type for the test if you prefer. I also extended the `Color` trait to have more than 4 subtypes to demonstrate the unknown order problem. Not many comments in the code so didn't add one but happy to put one in if you think it would be helpful.
> Sort subtypes to ensure consistent ordering (#195)

- core/shared/src/main/scala/magnolia.scala
- tests/src/main/scala/tests.scala
The issue was related to how we combine the Eithers into the target type. We were building a tuple the size of the case class, but tuples have limits that case classes don't have (anymore). 
So my solution is to limit the size of the tuples we do. If we had `ap` and curried functions, this wouldn't be an issue, but we don't have that atm.
> Fix #193: Tuple 22 issue

- core/shared/src/main/scala/magnolia.scala
- tests/src/main/java/magnolia/tests/WeekDay.java
- tests/src/main/scala/tests.scala
Java enums are considered sealed but are not traits.
Ref #137
> Fix ugly error message for Java enums

- core/shared/src/main/scala/magnolia.scala
- tests/src/main/scala/tests.scala
> Bite the bullet and use a regex to handle synthetic accessors

- tests/src/main/scala/tests.scala
`javax.annotation` is not part of the JDK since Java 11.
> Replace usage of javax annotation

- core/shared/src/main/scala/magnolia.scala
- tests/src/main/scala/tests.scala
Use sorted declarations of fields instead of getters.
Synthetic accessors might appear in arbitrary order.
Also remove unnecessary synthetic accessor name regex.
Fixes #215
> Fix derivation for case classes with partially private fields

- core/shared/src/main/scala/magnolia.scala
I don't see why semiauto should always be lazy.
Fixes #214
> Remove unnecessary condition for lazy val

- core/shared/src/main/scala/magnolia.scala
- tests/src/main/scala/tests.scala
As far as I can tell adding an `applied <:< genericType` subtype check fixes issue #228.
> Exclude invalid subtypes (#228)

- build.sbt
As reported on gitter:
```
Matthias Berndt @mberndt123 20:43
No, it's not fixed
It's still pulled in via mercator
mercator 0.2.1 has a normal (non-"Provided") dependency on scala-compiler, and magnolia 0.15.0 depends on mercator 0.2.1
Am I missing something here?
```
> Exclude scala-compiler too

- tests/src/main/scala/tests.scala
I was debugging a possible issue involving refined types and though this would be a good test example.
> Add test for deriving instances with refined types if implicit is in scope

- src/core/interface.scala
- src/core/magnolia.scala
- src/examples/objects.scala
- src/test/tests.scala
Fixes #164
This adds `isObject` as a parameter to `Subtype`.
One thing I was not sure on, is why the fallback implicit is required in traits used for testing (I see TypeNameInfo has it). This is only required for sealed traits which have a mixture of case classes and case objects.
> Added isObject to SealedTrait.Subtype

- build.sbt
- project/plugins.sbt
Cross-build for 2.12 and 2.13
Unfortunately, the tests only run using 2.12, as contextual (test dependency) is not available for 2.13.
> Build for Scala 2.13 as well
