core/src/main/scala/magnolia.scala, examples/src/main/scala/example.scala, tests/shared/src/main/scala/magnolia/main.scala
Adds support for typeclasses that takes 2 arguments of type T, new abstraction is called `ContravariantDerivation2`.
=> Support for deriving Eq (2-arg contravariant derivations)

core/src/main/scala/magnolia.scala, tests/src/main/scala/tests.scala
All publicly-visible names are now decoded.
=> Decode typeNames and labels

core/shared/src/main/scala/magnolia.scala
=> Avoid confusing error messages if `magnolia._` is not imported

core/shared/src/main/scala/magnolia.scala, tests/src/main/scala/tests.scala
Fixes https://github.com/propensive/magnolia/issues/41.
=> Avoid instantiating Unit when producing error stack

.gitignore, core/shared/src/main/scala/magnolia.scala, tests/src/main/scala/tests.scala
=> Fixed derivation error when companion has alternative apply methods

core/shared/src/main/scala/interface.scala, core/shared/src/main/scala/magnolia.scala, examples/shared/src/main/scala/patch.scala, tests/src/main/scala/tests.scala
and a new `Patcher[T]` example showing off what it can be used for.
This example also shows how https://github.com/propensive/magnolia/issues/58 would be great to have...
=> Add `CaseClass.rawConstruct`

core/shared/src/main/scala/magnolia.scala, tests/src/main/scala/tests.scala
There are a lot changes. Still need to rebase and resolve conflicts but should be possible to review like this.
Some design choices:
* Embrace a mutable stack (having a global case class `var allTheState` doesn't help, it just makes it cumbersome to modify without lenses).
* Add the typeclass constructor to stack frames and error messages (see #60)
* Also includes some clean-up (IMO) around `Option`s
fixes #44, fixes #60 and fixes #66
=> Rework compile time stack

.travis.yml, CHANGES, build.sbt, project/build.properties, project/plugins.sbt
Also add a simple travis build config and compile magnolia for Scala 2.13.0-M3.
Closes #36
=> Cross-build for Scala Native

core/shared/src/main/scala/magnolia.scala, examples/shared/src/main/scala/decode.scala
=> use toList instead of to[List]

core/shared/src/main/scala/magnolia.scala
=> Calculate all leaf nodes for knownDirectSubclasses

build.sbt
These options removed or deprecated
- https://github.com/scala/scala/commit/ad25805de5c63084348348aabefdf184927806c2
- https://github.com/scala/scala/commit/7d5e0b01c7f645e4f727f704a18f93ce5c69a9dd
=> fix scalacOptions for latest Scala 2.13.x

core/shared/src/main/scala/magnolia.scala, tests/src/main/scala/tests.scala
=> don't assume fullauto derivation

core/shared/src/main/scala/magnolia.scala
Fix for https://github.com/propensive/magnolia/issues/138
=> Dot not derive TC for case classes with private constructor

core/shared/src/main/scala/magnolia.scala
=> Minor speed improvements

core/shared/src/main/scala/magnolia.scala
This should eliminate a warning during compilation
=> Make inner Frame class non-final

core/shared/src/main/scala/magnolia.scala, tests/src/main/scala/tests.scala
https://github.com/propensive/magnolia/issues/138#issuecomment-536532038
=> enable derivation of case class with private constructors

core/shared/src/main/scala/magnolia.scala
This PR closes https://github.com/propensive/magnolia/issues/191.
=> Use `collect` instead of `left.get`

core/shared/src/main/scala/magnolia.scala
This PR closes https://github.com/propensive/magnolia/issues/198.
=> Do not infer the type of the underlying eithers

core/shared/src/main/scala/magnolia.scala, tests/src/main/scala/tests.scala
Closes #189, closes #165, closes #82
=> Fix ugly error when trying to derive for refined types

examples/shared/src/main/scala/patch.scala
https://github.com/scala/scala/commit/88546d78d0ae45742acb4f91cc16c904038f8b5b
=> avoid deprecated unicode arrow

build.sbt, core/shared/src/main/scala/interface.scala, core/shared/src/main/scala/magnolia.scala, tests/src/main/scala/tests.scala
https://github.com/scala/scala/blob/v2.13.1/src/library/scala/languageFeature.scala#L35
=> avoid deprecated "import scala.language.higherKinds"

core/shared/src/main/scala/magnolia.scala
Hoping that this will solve issues when using the Hydra compiler.
Ref #216 but I'm not sure if it actually fixes the problem.
=> Use ThreadLocal stack and workset

core/shared/src/main/scala/magnolia.scala, tests/src/main/scala/tests.scala
Also fix error message assertion for Java 11+
Fixes #225
=> Fix caseClassParameters for value case classes

core/shared/src/main/scala/magnolia.scala, tests/src/main/scala/tests.scala
=> Fix default parameters computation

core/shared/src/main/scala/magnolia.scala
Minor fix that supports the usage of @debug meaning no filtering, same as @debug("").
Currently using @debug  or @debug() would not print out anything which is unexpected as per the
interface definition. It also triggers an error case if wrong parameters are passed like constructing @debug with a non literal string.
=> Fix @debug with empty constructor so @debug behaves like @debug("")

core/shared/src/main/scala/magnolia.scala
Bug was introduced in #224, we missed it during review.
=> Fix annotations of ReadOnlyParam by eliminating code duplication

core/shared/src/main/scala/magnolia.scala, tests/src/main/scala/tests.scala
... and that all classes are final or case classes.
Otherwise the act as an escape hatch (can be extended).'
And make use of `collect`.
Closes #243
=> Add check that all traits in a hierarchy are sealed

core/shared/src/main/scala/magnolia.scala, examples/shared/src/main/scala/show.scala, tests/src/main/scala/tests.scala
This time handling type mismatch for generic parameters.
Fixes #244
=> Another way of getting default parameter values

core/shared/src/main/scala/magnolia.scala
=> Tweak companionOf to add a fast path when it works

core/shared/src/main/scala/magnolia.scala, tests/src/main/scala/NoCombine.scala, tests/src/main/scala/tests.scala
=> Support dispatch without combine

core/shared/src/main/scala/magnolia.scala
Over time the code has become messy and duplicated.
* Use object, type and symbol constants instead of untyped trees
* Use constants from `definitions` where possible
* Factor out `construct*` helper methods
=> A lot of refactoring

build.sbt, src/test/magnolia/tests/tests.scala
=> Migrates tests to munit

readme.md
The previous example in README did not work. I have aligned the naming convention with the `examples` (Show -> Print) and changed a little bit code so it compiles and works.
=> Update of readme to working example

src/core/macro.scala, src/test/tests.scala
=> Fix owner name

src/core/macro.scala, src/core/magnolia.scala, src/test/tests.scala
Addresses #296 point 4 - `accessing annotations`
=> Type annotations

build.sbt, src/test/magnolia/tests/tests.scala
The weird project structure still makes it hard to work with though
=> Fix legacy branch tests

build.sbt, test/src/test/scala/magnolia/tests/tests.scala
=> Remove contextual dependencies

core/src/main/scala/magnolia/magnolia.scala
Those error messages are never shown to the user.
Also move directly reentrant error before allocating constants.
=> Optimization - skip error messages at depth > 1
